apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: application
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
