apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: application
    server: 'https://kubernetes.default.svc'
  source:
    path: frontend
    repoURL: https://github.com/YOUR_USERNAME/deployments-gitops
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
