apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db
  namespace: argocd
spec: 
  project: default

  source:
    repoURL: https://github.com/Harshita878/3rd-party-repo.git 
    targetRevision: HEAD  
    path: postgresql   
    helm:
      valueFiles:
      - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: application              

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
